-- ============================================================================
--  SUBSTITUTE TEACHER ACCESS  (2026-07-29)
--  Paste-run ang BUONG file sa Supabase ▸ SQL Editor. Safe to re-run.
--
--  ANO ITO: kapag nag-leave ang isang teacher, pwedeng IBAHAGI ng Academic
--  Coordinator ang grade sheet niya sa isang SUBSTITUTE. Lalabas agad ang
--  sheet sa Gradebook ng substitute at pwede na siyang mag-encode. Pagbalik
--  ng orihinal na teacher, ISASARA ng coordinator ang access sa isang pindot.
--
--  MAHALAGANG DISENYO — ang sheet ay MANANATILING PAG-AARI ng orihinal na
--  teacher. Hindi inaalis ang load niya; hindi nagbabago ang approval routing;
--  ang review states (sas_grade_reviews) ay naka-key pa rin sa kanya. Ang
--  substitute ay may HIRAM na access lang — kaya walang nasisira sa records
--  kahit ilang beses pang magpalit ng substitute.
--
--  ANO ANG NAAABOT NG SUBSTITUTE:
--   • Nakikita ang sheet sa sariling Gradebook (may "Substitute" badge).
--   • Nakaka-encode ng scores/attitude sa mga term na SAKOP ng grant.
--   • Nakikita ang locks (na-submit na sa Registrar) at ang mga returned
--     na term ng may-ari, at pwedeng i-Mark as resolved.
--   • HINDI nakikita ang ibang sheet ng may-ari na hindi ibinahagi.
--
--  Nakadepende sa mga EXISTING na function: current_teacher_id(),
--  is_acad_for(), reg_ac_role_for(). Hindi ito ginagalaw dito.
-- ============================================================================


-- ═══ PART 1 — ang talaan ng mga ibinahaging sheet ═══════════════════════════

create table if not exists public.reg_substitutes (
  id               bigint generated by default as identity primary key,
  class_id         uuid   not null references public.reg_classes(id)  on delete cascade,
  subject_code     text   not null references public.reg_subjects(code) on delete cascade,
  owner_teacher_id bigint not null references public.reg_teachers(id) on delete cascade,
  sub_teacher_id   bigint not null references public.reg_teachers(id) on delete cascade,
  -- Comma-joined period keys ('q2,q3'). NULL = lahat ng term na sakop ng may-ari.
  terms            text,
  note             text,
  granted_by       text,
  granted_at       timestamptz not null default now(),
  ended_by         text,
  ended_at         timestamptz,          -- NULL = AKTIBO pa
  constraint reg_substitutes_not_self check (owner_teacher_id <> sub_teacher_id)
);

comment on table public.reg_substitutes is
  'Hiram na access sa grade sheet ng naka-leave na teacher. ended_at null = aktibo. Hindi nito inaalis ang load ng may-ari.';

-- Isang AKTIBONG grant lang bawat (section, subject, substitute).
create unique index if not exists reg_substitutes_active_uniq
  on public.reg_substitutes (class_id, subject_code, sub_teacher_id)
  where ended_at is null;

create index if not exists reg_substitutes_sub_active_idx
  on public.reg_substitutes (sub_teacher_id) where ended_at is null;

alter table public.reg_substitutes enable row level security;
-- Sadyang WALANG policies: ang gated RPCs (security definer) lang ang daanan.


-- ═══ PART 2 — caller helpers ════════════════════════════════════════════════

-- Kung ang CALLER ay aktibong substitute sa (class, subject) — at sakop ng
-- grant ang term — ibinabalik nito ang teacher id ng MAY-ARI. NULL kung hindi.
-- p_period null = huwag suriin ang term (pang-authorization sa buong sheet).
create or replace function public.sub_owner_for(
  p_class_id uuid, p_subject_code text, p_period text default null)
returns bigint
language sql stable security definer set search_path to 'public'
as $$
  select s.owner_teacher_id
  from reg_substitutes s
  where s.ended_at is null
    and s.class_id = p_class_id
    and s.subject_code = p_subject_code
    and s.sub_teacher_id = public.current_teacher_id()
    and (p_period is null or s.terms is null
         or p_period = any (string_to_array(s.terms, ',')))
  limit 1;
$$;
grant execute on function public.sub_owner_for(uuid, text, text) to authenticated;

-- Ang mga TERM na sakop ng grant ng caller sa isang sheet ('{q2,q3}').
-- NULL = walang hangganan sa term (lahat ng sakop ng may-ari).
create or replace function public.sub_terms_for(p_class_id uuid, p_subject_code text)
returns text[]
language sql stable security definer set search_path to 'public'
as $$
  select case when s.terms is null then null
              else string_to_array(s.terms, ',') end
  from reg_substitutes s
  where s.ended_at is null
    and s.class_id = p_class_id
    and s.subject_code = p_subject_code
    and s.sub_teacher_id = public.current_teacher_id()
  limit 1;
$$;
grant execute on function public.sub_terms_for(uuid, text) to authenticated;

-- Lahat ng may-ari na pinapalitan ng caller sa isang subject (kahit aling
-- section) — para sa review/lock states na naka-key sa teacher × subject.
create or replace function public.sub_owners_of_subject(p_subject_code text)
returns bigint[]
language sql stable security definer set search_path to 'public'
as $$
  select coalesce(array_agg(distinct s.owner_teacher_id), '{}'::bigint[])
  from reg_substitutes s
  where s.ended_at is null
    and s.sub_teacher_id = public.current_teacher_id()
    and s.subject_code = p_subject_code;
$$;
grant execute on function public.sub_owners_of_subject(text) to authenticated;


-- ═══ PART 3 — coordinator: magbahagi / magsara / tingnan ════════════════════

-- Ibahagi ang isang sheet sa substitute. Ang MAY-ARI ay kinukuha sa aktwal na
-- load ng section (kaya walang mali kung sino ang pinapalitan).
--  p_terms: null = lahat ng term na sakop ng may-ari; 'q2,q3' = ang mga ito lang.
--  Kapag naibahagi na dati sa parehong substitute, ina-update lang ang terms/note.
create or replace function public.acad_grant_substitute(
  p_class_id uuid,
  p_subject_code text,
  p_sub_teacher_id bigint,
  p_terms text default null,
  p_note text default null)
returns bigint
language plpgsql security definer set search_path to 'public'
as $function$
declare
  v_by      text := auth.jwt() ->> 'email';
  v_grade   text;
  v_teacher bigint;
  v_term    text;
  v_tt      jsonb;
  v_owner   bigint;
  v_cover   text[];      -- ang term coverage ng may-ari (null = buong taon)
  v_want    text[];      -- ang hinihinging terms (null = lahat)
  v_k       text;
  v_owners  bigint[];
  v_id      bigint;
begin
  select c.grade_level into v_grade
  from reg_classes c
  where c.id = p_class_id and public.is_acad_for(c.grade_level);
  if v_grade is null then
    raise exception 'Not authorized for this section';
  end if;

  select cs.teacher_id, cs.term, cs.term_teachers
    into v_teacher, v_term, v_tt
  from reg_class_subjects cs
  where cs.class_id = p_class_id and cs.subject_code = p_subject_code;

  if not found then
    raise exception 'Subject % is not in this section', p_subject_code;
  end if;

  v_want := case when coalesce(p_terms, '') = '' then null
                 else string_to_array(p_terms, ',') end;
  if v_want is not null then
    foreach v_k in array v_want loop
      if v_k !~ '^q[1-4]$' then
        raise exception 'Invalid term key: %', v_k;
      end if;
    end loop;
  end if;

  if v_tt is null then
    -- Karaniwang subject: iisa ang may-ari.
    if v_teacher is null then
      raise exception 'Walang nakatalagang guro sa % — mag-assign muna bago magbahagi', p_subject_code;
    end if;
    v_owner := v_teacher;
    v_cover := case when v_term is null then null else string_to_array(v_term, ',') end;
  else
    -- Rotating/combination subject: iba-iba ang may-ari kada term, kaya
    -- KAILANGANG tukuyin ang term(s) — at iisa lang dapat ang may-ari nila.
    if v_want is null then
      raise exception 'Rotating subject ang % — piliin kung aling term(s) ang ibabahagi', p_subject_code;
    end if;
    select coalesce(array_agg(distinct (v_tt ->> k)::bigint), '{}'::bigint[])
      into v_owners
    from unnest(v_want) k
    where (v_tt ->> k) ~ '^\d+$';
    if coalesce(array_length(v_owners, 1), 0) = 0 then
      raise exception 'Walang nakatalagang guro sa mga piniling term ng %', p_subject_code;
    end if;
    if array_length(v_owners, 1) > 1 then
      raise exception 'Magkaibang guro ang may hawak ng mga piniling term — isahin ang pagbabahagi kada guro';
    end if;
    v_owner := v_owners[1];
    select coalesce(array_agg(k order by k), '{}'::text[]) into v_cover
    from jsonb_each_text(v_tt) as e(k, v)
    where v ~ '^\d+$' and v::bigint = v_owner;
  end if;

  -- Ang hinihinging term ay dapat SAKOP ng may-ari — walang maibabahaging
  -- term na hindi naman kanya.
  if v_want is not null and v_cover is not null then
    foreach v_k in array v_want loop
      if not (v_k = any (v_cover)) then
        raise exception 'Hindi sakop ng may-ari ang term % sa %', v_k, p_subject_code;
      end if;
    end loop;
  end if;

  if p_sub_teacher_id = v_owner then
    raise exception 'Ang guro mismo ang may hawak ng sheet na ito';
  end if;
  if not exists (select 1 from reg_teachers t
                 where t.id = p_sub_teacher_id and coalesce(t.year_ended, 0) = 0) then
    raise exception 'Substitute teacher not found or no longer active';
  end if;

  insert into reg_substitutes (class_id, subject_code, owner_teacher_id, sub_teacher_id,
                               terms, note, granted_by)
  values (p_class_id, p_subject_code, v_owner, p_sub_teacher_id,
          nullif(p_terms, ''), nullif(p_note, ''), v_by)
  on conflict (class_id, subject_code, sub_teacher_id) where ended_at is null
  do update set terms = excluded.terms,
                note = excluded.note,
                owner_teacher_id = excluded.owner_teacher_id,
                granted_by = excluded.granted_by,
                granted_at = now()
  returning id into v_id;

  return v_id;
end;
$function$;
grant execute on function public.acad_grant_substitute(uuid, text, bigint, text, text) to authenticated;


-- Isara ang access (pagbalik ng naka-leave na teacher). Hindi binubura ang
-- row — nananatili itong record kung sino ang humawak at hanggang kailan.
create or replace function public.acad_end_substitute(p_id bigint)
returns void
language plpgsql security definer set search_path to 'public'
as $function$
declare v_grade text;
begin
  select c.grade_level into v_grade
  from reg_substitutes s
  join reg_classes c on c.id = s.class_id
  where s.id = p_id and public.is_acad_for(c.grade_level);
  if v_grade is null then
    raise exception 'Not authorized for this section';
  end if;

  update reg_substitutes
     set ended_at = now(), ended_by = auth.jwt() ->> 'email'
   where id = p_id and ended_at is null;
  if not found then
    raise exception 'Sarado na ang access na ito';
  end if;
end;
$function$;
grant execute on function public.acad_end_substitute(bigint) to authenticated;


-- Listahan para sa coordinator. p_owner_teacher_id = ang naka-leave na guro
-- (ang page na binubuksan); p_include_ended = isama ang mga sarado na.
create or replace function public.acad_substitutes(
  p_owner_teacher_id bigint default null,
  p_include_ended boolean default false)
returns table(
  id bigint, class_id uuid, sy text, grade_level text, section_name text,
  subject_code text, subject_name text,
  owner_teacher_id bigint, owner_name text,
  sub_teacher_id bigint, sub_name text,
  terms text, note text,
  granted_by text, granted_at timestamptz,
  ended_by text, ended_at timestamptz)
language sql stable security definer set search_path to 'public'
as $$
  select s.id, c.id, c.sy, c.grade_level, c.section_name,
         s.subject_code, coalesce(subj.full_name, s.subject_code),
         s.owner_teacher_id,
         nullif(trim(coalesce(o.first_name,'') || ' ' || coalesce(o.family_name,'')), ''),
         s.sub_teacher_id,
         nullif(trim(coalesce(b.first_name,'') || ' ' || coalesce(b.family_name,'')), ''),
         s.terms, s.note, s.granted_by, s.granted_at, s.ended_by, s.ended_at
  from reg_substitutes s
  join reg_classes c on c.id = s.class_id
  join reg_teachers o on o.id = s.owner_teacher_id
  join reg_teachers b on b.id = s.sub_teacher_id
  left join reg_subjects subj on subj.code = s.subject_code
  where public.is_acad_for(c.grade_level)
    and (p_owner_teacher_id is null or s.owner_teacher_id = p_owner_teacher_id)
    and (p_include_ended or s.ended_at is null)
  order by s.ended_at nulls first, s.granted_at desc;
$$;
grant execute on function public.acad_substitutes(bigint, boolean) to authenticated;


-- ═══ PART 4 — teacher side: nakikita na ang hiram na sheet ══════════════════

-- teacher_my_load: bukod sa SARILING load, kasama na ang mga sheet na
-- IBINAHAGI sa caller bilang substitute. Bagong columns kaya drop muna.
drop function if exists public.teacher_my_load();

create function public.teacher_my_load()
returns table(class_id uuid, sy text, grade_level text, section_name text,
              subject_code text, subject_name text, term text, is_combo boolean,
              is_substitute boolean, owner_teacher_id bigint, owner_name text,
              substitute_id bigint)
language sql stable security definer set search_path to 'public'
as $$
  -- 1) sariling load (karaniwang subject)
  select c.id, c.sy, c.grade_level, c.section_name,
         cs.subject_code, coalesce(s.full_name, cs.subject_code), cs.term, false,
         false, null::bigint, null::text, null::bigint
  from reg_class_subjects cs
  join reg_classes c on c.id = cs.class_id
  left join reg_subjects s on s.code = cs.subject_code
  where cs.term_teachers is null and cs.teacher_id = public.current_teacher_id()
  union all
  -- 2) sariling load (rotating: term ko lang ang ipinapakita)
  select c.id, c.sy, c.grade_level, c.section_name,
         cs.subject_code, coalesce(s.full_name, cs.subject_code),
         (select string_agg(e.key, ',' order by e.key)
          from jsonb_each_text(cs.term_teachers) e
          where (case when e.value ~ '^\d+$' then e.value::bigint end) = public.current_teacher_id()),
         true,
         false, null::bigint, null::text, null::bigint
  from reg_class_subjects cs
  join reg_classes c on c.id = cs.class_id
  left join reg_subjects s on s.code = cs.subject_code
  where cs.term_teachers is not null
    and exists (select 1 from jsonb_each_text(cs.term_teachers) e
                where (case when e.value ~ '^\d+$' then e.value::bigint end) = public.current_teacher_id())
  union all
  -- 3) HIRAM na sheet (substitute). Ang term ay ang sakop ng grant; kapag
  --    walang tinukoy, ang buong coverage ng may-ari.
  select c.id, c.sy, c.grade_level, c.section_name,
         cs.subject_code, coalesce(s.full_name, cs.subject_code),
         coalesce(
           sub.terms,
           case when cs.term_teachers is null then cs.term
                else (select string_agg(e.key, ',' order by e.key)
                      from jsonb_each_text(cs.term_teachers) e
                      where (case when e.value ~ '^\d+$' then e.value::bigint end)
                            = sub.owner_teacher_id) end),
         cs.term_teachers is not null,
         true, sub.owner_teacher_id,
         nullif(trim(coalesce(o.first_name,'') || ' ' || coalesce(o.family_name,'')), ''),
         sub.id
  from reg_substitutes sub
  join reg_classes c on c.id = sub.class_id
  join reg_class_subjects cs
       on cs.class_id = sub.class_id and cs.subject_code = sub.subject_code
  join reg_teachers o on o.id = sub.owner_teacher_id
  left join reg_subjects s on s.code = sub.subject_code
  where sub.ended_at is null
    and sub.sub_teacher_id = public.current_teacher_id()
    -- Kung may SARILING load na ang caller sa parehong sheet, huwag nang
    -- ulitin bilang hiram — ang sarili niyang access ang mas malawak.
    and not (cs.teacher_id = public.current_teacher_id()
             or (cs.term_teachers is not null and exists (
                   select 1 from jsonb_each_text(cs.term_teachers) e
                   where (case when e.value ~ '^\d+$' then e.value::bigint end)
                         = public.current_teacher_id())))
  order by 3, 4, 6;
$$;
grant execute on function public.teacher_my_load() to authenticated;


-- Roster ng isang section na hiniram ng substitute. Hiwalay sa
-- teacher_class_roster para HINDI magalaw ang umiiral na guard ng may-ari.
create or replace function public.substitute_class_roster(p_class_id uuid)
returns table(lrn text, last_name text, first_name text, middle_name text,
              extension text, gender text, grades jsonb)
language plpgsql stable security definer set search_path to 'public'
as $function$
begin
  if not exists (
    select 1 from reg_substitutes s
    where s.ended_at is null
      and s.class_id = p_class_id
      and s.sub_teacher_id = public.current_teacher_id()
  ) then
    raise exception 'Walang ibinahaging grade sheet sa iyo sa section na ito';
  end if;
  return query
    select st.lrn, st.last_name, st.first_name, st.middle_name,
           st.extension, st.gender, st.grades
    from reg_students_data st
    where st.current_class_id = p_class_id
    order by st.last_name, st.first_name;
end;
$function$;
grant execute on function public.substitute_class_roster(uuid) to authenticated;


-- ═══ PART 5 — pag-save: pinapayagan na ang substitute (sakop na term lang) ══
-- Kapareho ng bersyon sa setup-combination-subjects.sql, may dagdag na
-- substitute branch. Ang isinusulat ay napupunta pa rin sa sheet ng may-ari.

create or replace function public.teacher_save_grades(
  p_lrn text, p_sy text, p_subject_code text, p_entry jsonb
) returns void
language plpgsql security definer set search_path to 'public'
as $function$
declare
  v_me bigint := public.current_teacher_id();
  v_class uuid;
  v_grades jsonb;
  v_arr jsonb;
  v_existing jsonb;
  v_entry jsonb;
  v_teacher bigint;   -- the row's single/primary teacher
  v_term text;        -- the row's term coverage
  v_tt jsonb;         -- the row's per-term teacher map (null = single teacher)
  v_sub_owner bigint; -- kapag substitute ang caller: ang may-ari ng sheet
  v_sub_terms text[]; -- ang term na sakop ng grant (null = walang hangganan)
  v_as bigint;        -- kung KANINONG pangalan kumikilos ang caller
  v_pk text;
  v_found boolean;
  v_final numeric;
  v_n integer := 0;
  v_sum numeric := 0;
begin
  if v_me is null then
    raise exception 'Not a teacher';
  end if;
  if p_lrn is null or p_sy is null or p_subject_code is null or p_entry is null then
    raise exception 'Missing arguments';
  end if;
  if coalesce(p_entry->>'subjectCode', '') <> p_subject_code then
    raise exception 'Subject code mismatch';
  end if;
  select current_class_id, grades into v_class, v_grades
  from reg_students_data where lrn = p_lrn;
  if v_class is null then
    raise exception 'Learner not found or not enrolled in a class';
  end if;

  select true, cs.teacher_id, cs.term, cs.term_teachers
    into v_found, v_teacher, v_term, v_tt
  from reg_class_subjects cs
  where cs.class_id = v_class and cs.subject_code = p_subject_code;

  if v_found is not true or (v_tt is null and v_teacher is null) then
    raise exception 'Subject % is not assigned in this class', p_subject_code;
  end if;

  -- Substitute access (kung meron) — dito lang nakukuha ang may-ari, kaya
  -- walang ibang paraan para mag-angkin ng sheet.
  v_sub_owner := public.sub_owner_for(v_class, p_subject_code, null);
  v_sub_terms := case when v_sub_owner is null then null
                      else public.sub_terms_for(v_class, p_subject_code) end;
  -- Ang identity na ginagamit sa mga guard sa ibaba: sarili, o ang may-ari
  -- kapag humihiram.
  v_as := coalesce(v_sub_owner, v_me);

  -- Authorization: hawak ng caller ang row, may hawak siyang term ng rotating
  -- subject, O may aktibong substitute grant siya rito.
  if not coalesce(
       (v_tt is null and v_teacher = v_as)
    or (v_tt is not null and exists (
          select 1 from jsonb_each_text(v_tt) e
          where (case when e.value ~ '^\d+$' then e.value::bigint end) = v_as)),
    false) then
    raise exception 'Not authorized to grade this subject for this learner';
  end if;

  select e into v_existing
  from jsonb_array_elements(coalesce(coalesce(v_grades, '{}'::jsonb) -> p_sy, '[]'::jsonb)) e
  where e->>'subjectCode' = p_subject_code
  limit 1;

  -- ── Substitute guard: ang term na WALA sa grant ay dapat dumating na
  --    walang pagbabago — hiram lang ang mga term na ibinigay. ──
  if v_sub_owner is not null and v_sub_terms is not null then
    foreach v_pk in array array['q1','q2','q3','q4'] loop
      if not (v_pk = any (v_sub_terms)) then
        if (p_entry -> v_pk)                is distinct from (v_existing -> v_pk)
        or (p_entry -> 'raw'      -> v_pk)  is distinct from (v_existing -> 'raw'      -> v_pk)
        or (p_entry -> 'items'    -> v_pk)  is distinct from (v_existing -> 'items'    -> v_pk)
        or (p_entry -> 'attitude' -> v_pk)  is distinct from (v_existing -> 'attitude' -> v_pk)
        or (p_entry -> 'letters'  -> v_pk)  is distinct from (v_existing -> 'letters'  -> v_pk)
        then
          raise exception
            'Term % ng % ay wala sa ibinahaging access sa iyo.', v_pk, p_subject_code;
        end if;
      end if;
    end loop;
  end if;

  -- ── Combination guard: ang term ng IBANG guro ay dapat dumating na walang
  --    pagbabago. (Bilang substitute, ang may-ari ang batayan.) ──
  if v_tt is not null then
    foreach v_pk in array array['q1','q2','q3','q4'] loop
      if (case when (v_tt ->> v_pk) ~ '^\d+$' then (v_tt ->> v_pk)::bigint end)
         is distinct from v_as then
        if (p_entry -> v_pk)                is distinct from (v_existing -> v_pk)
        or (p_entry -> 'raw'      -> v_pk)  is distinct from (v_existing -> 'raw'      -> v_pk)
        or (p_entry -> 'items'    -> v_pk)  is distinct from (v_existing -> 'items'    -> v_pk)
        or (p_entry -> 'attitude' -> v_pk)  is distinct from (v_existing -> 'attitude' -> v_pk)
        or (p_entry -> 'letters'  -> v_pk)  is distinct from (v_existing -> 'letters'  -> v_pk)
        then
          raise exception
            'Term % of % is handled by another teacher and cannot be edited here.', v_pk, p_subject_code;
        end if;
      end if;
    end loop;
  end if;

  -- ── SAS lock: ang term na na-submit na sa Registrar ay dapat dumating na
  --    walang pagbabago — umiiral din ito sa substitute. ──
  for v_pk in
    select r.period from sas_grade_reviews r
    where r.subject_code = p_subject_code
      and r.sy = p_sy
      and r.status = 'submitted'
      and ( (v_tt is null and r.teacher_id = v_teacher
             and (v_term is null or r.period = any(string_to_array(v_term, ','))))
         or (v_tt is not null
             and (case when (v_tt ->> r.period) ~ '^\d+$' then (v_tt ->> r.period)::bigint end)
                 = r.teacher_id) )
  loop
    if (p_entry -> v_pk)                is distinct from (v_existing -> v_pk)
    or (p_entry -> 'raw'      -> v_pk)  is distinct from (v_existing -> 'raw'      -> v_pk)
    or (p_entry -> 'items'    -> v_pk)  is distinct from (v_existing -> 'items'    -> v_pk)
    or (p_entry -> 'attitude' -> v_pk)  is distinct from (v_existing -> 'attitude' -> v_pk)
    or (p_entry -> 'letters'  -> v_pk)  is distinct from (v_existing -> 'letters'  -> v_pk)
    then
      raise exception
        'Term % of % was submitted to the Registrar and can no longer be edited.', v_pk, p_subject_code;
    end if;
  end loop;

  -- final ay DERIVED, hindi kailanman tinatanggap mula sa client.
  v_entry := p_entry;
  foreach v_pk in array array['q1','q2','q3','q4'] loop
    if jsonb_typeof(v_entry -> v_pk) = 'number' then
      v_n := v_n + 1;
      v_sum := v_sum + (v_entry ->> v_pk)::numeric;
    end if;
  end loop;
  if v_n > 0 then
    v_final := round(v_sum / v_n);
    v_entry := jsonb_set(v_entry, array['final'], to_jsonb(v_final), true);
  elsif v_existing ? 'final' then
    v_entry := jsonb_set(v_entry, array['final'], v_existing -> 'final', true);
  else
    v_entry := v_entry - 'final';
  end if;

  v_grades := coalesce(v_grades, '{}'::jsonb);
  v_arr := coalesce(v_grades -> p_sy, '[]'::jsonb);
  select coalesce(jsonb_agg(e), '[]'::jsonb) into v_arr
  from jsonb_array_elements(v_arr) e
  where e->>'subjectCode' is distinct from p_subject_code;
  v_arr := v_arr || jsonb_build_array(v_entry);
  v_grades := jsonb_set(v_grades, array[p_sy], v_arr, true);
  update reg_students_data set grades = v_grades where lrn = p_lrn;
end;
$function$;
grant execute on function public.teacher_save_grades(text, text, text, jsonb) to authenticated;


-- ═══ PART 6 — locks at returned-for-revision, kita rin ng substitute ════════

-- teacher_locked_terms: kasama na ang lock ng MAY-ARI sa mga subject na
-- hiniram ng caller — para read-only agad ang na-submit nang term sa kanya.
create or replace function public.teacher_locked_terms()
returns table(subject_code text, sy text, period text, submitted_at timestamptz)
language sql stable security definer set search_path to 'public'
as $$
  select r.subject_code, r.sy, r.period, r.submitted_at
  from sas_grade_reviews r
  where r.status = 'submitted'
    and ( r.teacher_id = public.current_teacher_id()
       or exists (
            select 1 from reg_class_subjects cs
            where cs.subject_code = r.subject_code
              and cs.term_teachers is not null
              and (case when (cs.term_teachers ->> r.period) ~ '^\d+$'
                        then (cs.term_teachers ->> r.period)::bigint end) = r.teacher_id
              and exists (select 1 from jsonb_each_text(cs.term_teachers) e
                          where (case when e.value ~ '^\d+$' then e.value::bigint end)
                                = public.current_teacher_id()) )
       -- Hiram na sheet: ang lock ng may-ari ay lock din sa substitute.
       or ( r.teacher_id = any (public.sub_owners_of_subject(r.subject_code))
            -- Huwag i-lock kung may SARILING load ang caller sa subject na
            -- ito — iba ang sheet na iyon at hindi ito nakatali sa may-ari.
            and not exists (
              select 1 from reg_class_subjects cs2
              where cs2.subject_code = r.subject_code
                and (cs2.teacher_id = public.current_teacher_id()
                     or (cs2.term_teachers is not null and exists (
                           select 1 from jsonb_each_text(cs2.term_teachers) e2
                           where (case when e2.value ~ '^\d+$' then e2.value::bigint end)
                                 = public.current_teacher_id())))) ) );
$$;
grant execute on function public.teacher_locked_terms() to authenticated;

-- teacher_my_revisions / ack / mark-resolved: gumagana na rin sa hiram na sheet,
-- para matapos ng substitute ang ibinalik na term ng naka-leave na teacher.
create or replace function public.teacher_my_revisions()
returns table(subject_code text, subject_name text, sy text, period text,
              note text, returned_at timestamptz, needs_popup boolean)
language sql stable security definer set search_path to 'public'
as $$
  select r.subject_code, coalesce(s.full_name, r.subject_code), r.sy, r.period,
         r.note, r.returned_at, (not r.popup_seen) as needs_popup
  from sas_grade_reviews r
  left join reg_subjects s on s.code = r.subject_code
  where r.status = 'needs_revision'
    and ( r.teacher_id = public.current_teacher_id()
       or r.teacher_id = any (public.sub_owners_of_subject(r.subject_code)) )
  order by r.returned_at desc;
$$;
grant execute on function public.teacher_my_revisions() to authenticated;

create or replace function public.teacher_ack_revision_popup(
  p_subject_code text, p_sy text, p_period text)
returns void language plpgsql security definer set search_path to 'public'
as $$
begin
  update sas_grade_reviews
     set popup_seen = true, updated_at = now()
   where subject_code = p_subject_code and sy = p_sy and period = p_period
     and ( teacher_id = public.current_teacher_id()
        or teacher_id = any (public.sub_owners_of_subject(p_subject_code)) );
end;
$$;
grant execute on function public.teacher_ack_revision_popup(text, text, text) to authenticated;

create or replace function public.teacher_mark_resolved(
  p_subject_code text, p_sy text, p_period text)
returns void language plpgsql security definer set search_path to 'public'
as $$
begin
  update sas_grade_reviews
     set status = 'for_rechecking', popup_seen = true, updated_at = now()
   where subject_code = p_subject_code and sy = p_sy and period = p_period
     and status = 'needs_revision'
     and ( teacher_id = public.current_teacher_id()
        or teacher_id = any (public.sub_owners_of_subject(p_subject_code)) );
  if not found then
    raise exception 'No pending revision for this subject/term';
  end if;
end;
$$;
grant execute on function public.teacher_mark_resolved(text, text, text) to authenticated;


notify pgrst, 'reload schema';


-- ═══ VERIFY — dapat 'true' lahat ═══════════════════════════════════════════
select 'reg_substitutes table' as item,
       (to_regclass('public.reg_substitutes') is not null)::text as ok
union all
select 'coordinator RPCs (3)',
       ((select count(*) from pg_proc p join pg_namespace n on n.oid = p.pronamespace
         where n.nspname = 'public'
           and p.proname in ('acad_grant_substitute','acad_end_substitute','acad_substitutes')) = 3)::text
union all
select 'teacher_my_load has is_substitute',
       (pg_get_functiondef('public.teacher_my_load()'::regprocedure) like '%is_substitute%')::text
union all
select 'teacher_save_grades honors substitutes',
       (pg_get_functiondef('public.teacher_save_grades(text,text,text,jsonb)'::regprocedure)
        like '%sub_owner_for%')::text
union all
select 'substitute_class_roster',
       (to_regprocedure('public.substitute_class_roster(uuid)') is not null)::text;
