-- ════════════════════════════════════════════════════════════════════════
--  REGISTRAR SYSTEM — Supabase backend (shared NPS project)
--
--  Run this once in the NPS Supabase SQL editor. Tables are prefixed `reg_`
--  so they never clash with the payroll `teachers` table or other modules.
--  Access is limited to the 'registrar' and 'admin' roles via user_roles
--  (the same table the staff portal uses).
--
--  Grant a registrar (after their auth account exists):
--    insert into user_roles (user_email, role) values ('<email>', 'registrar')
--      on conflict (user_email) do update set role = excluded.role;
-- ════════════════════════════════════════════════════════════════════════

-- ── 0. role-check helper ────────────────────────────────────────────────
create or replace function public.is_registrar()
  returns boolean
  language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from user_roles
    where user_email = auth.jwt() ->> 'email'
      and role in ('registrar', 'admin')
  );
$$;

-- ── 1. school years ─────────────────────────────────────────────────────
create table if not exists reg_school_years (
  code        text primary key,          -- "2025-2026"
  label       text not null,             -- "SY 2025–2026"
  start_date  date,
  end_date    date,
  is_active   boolean not null default false,
  created_at  timestamptz default now()
);

-- ── 2. teachers (registrar's own list; separate from payroll) ────────────
create table if not exists reg_teachers (
  id              bigint generated by default as identity primary key,
  title           text default '',        -- "Mrs.", "Mr.", "Fr."
  family_name     text not null,
  first_name      text not null,
  middle_initial  text default '',
  email           text default '',
  year_started    int  default 0,
  year_ended      int  default 0,         -- 0 = still active (legacy convention)
  is_adviser      boolean default false,
  curriculum      text default '',
  created_at      timestamptz default now()
);

-- ── 3. subjects ─────────────────────────────────────────────────────────
create table if not exists reg_subjects (
  code          text primary key,         -- "FIL"
  full_name     text not null,
  abbreviation  text default '',
  category      text not null default 'Core'   -- Core | Specialized | Applied | Elective
);

-- ── 4. schools (transferee origin; first 6 digits of an LRN) ─────────────
create table if not exists reg_schools (
  code      text primary key,             -- 6-digit DepEd School ID
  name      text not null,
  address   text default '',
  district  text default '',
  division  text default '',
  region    text default '',
  type      text default ''               -- Public | Private | SUC
);
-- bring older deployments up to the current shape
alter table reg_schools add column if not exists address  text default '';
alter table reg_schools add column if not exists district text default '';
alter table reg_schools add column if not exists division text default '';
alter table reg_schools add column if not exists region   text default '';

-- ── 5. classes / sections (per school year) ──────────────────────────────
create table if not exists reg_classes (
  id            uuid primary key default gen_random_uuid(),
  sy            text not null references reg_school_years(code) on update cascade,
  grade_level   text not null,            -- N1 … XII-STEM
  section_name  text not null,            -- "St. John Vianney"
  adviser_id    bigint references reg_teachers(id) on delete set null,
  curriculum    text default '',
  created_at    timestamptz default now()
);
create index if not exists reg_classes_sy_idx on reg_classes (sy);

-- ── 6. students ─────────────────────────────────────────────────────────
-- Scalar columns for the searchable/identity fields; nested structures
-- (enrolment history, grades, credentials, NCAE/NAT) kept as JSONB so the
-- row shape mirrors the app's Student type with minimal mapping.
create table if not exists reg_students (
  lrn                         text primary key,            -- 12-digit
  student_no                  text default '',
  first_name                  text not null,
  middle_name                 text default '',
  last_name                   text not null,
  extension                   text default '',
  gender                      text default '',
  birthdate                   date,
  religion                    text default '',
  address                     text default '',
  contact_number              text default '',
  father_name                 text default '',
  mother_maiden_name          text default '',
  guardian_relation           text default 'Mother',
  current_sy                  text references reg_school_years(code) on update cascade,
  current_class_id            uuid references reg_classes(id) on delete set null,
  curriculum                  text default '',
  status                      text not null default 'Active',  -- Active | Dropped | Transferred | Graduated
  elem_school_graduated_from  text default '',
  school_type                 text default '',
  loyalty_years               int  default 0,
  enrolment_history           jsonb not null default '[]'::jsonb,
  grades                      jsonb not null default '{}'::jsonb,
  credentials                 jsonb not null default '{}'::jsonb,
  ncae                        jsonb,
  nat                         jsonb,
  created_at                  timestamptz default now(),
  updated_at                  timestamptz default now()
);
create index if not exists reg_students_sy_idx    on reg_students (current_sy);
create index if not exists reg_students_class_idx on reg_students (current_class_id);
create index if not exists reg_students_name_idx  on reg_students (last_name, first_name);

-- keep updated_at fresh
create or replace function reg_touch_updated_at() returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end; $$;
drop trigger if exists reg_students_touch on reg_students;
create trigger reg_students_touch before update on reg_students
  for each row execute function reg_touch_updated_at();

-- ── 7. Row Level Security — registrar + admin only ───────────────────────
do $$
declare t text;
begin
  foreach t in array array[
    'reg_school_years','reg_teachers','reg_subjects',
    'reg_schools','reg_classes','reg_students'
  ] loop
    execute format('alter table %I enable row level security', t);
    execute format('drop policy if exists "registrar full access" on %I', t);
    execute format(
      'create policy "registrar full access" on %I for all to authenticated
         using (public.is_registrar()) with check (public.is_registrar())', t);
  end loop;
end $$;

-- ── 8. seed: the active school year (so the SY selector has a value) ──────
-- SY 2026-2027 is the active year and uses THREE terms (see periodsForSy()).
insert into reg_school_years (code, label, start_date, end_date, is_active) values
  ('2025-2026', 'SY 2025–2026', '2025-06-01', '2026-03-31', false),
  ('2026-2027', 'SY 2026–2027', '2026-06-01', '2027-03-31', true)
on conflict (code) do update set is_active = excluded.is_active;

-- ── 9. seed: core subject catalog (legacy NPS Batch 9 codes) ─────────────
-- MAPEH is NOT a directly-graded subject: teachers grade its two components
-- ("Music & Arts" / "Physical Education & Health") and the app derives the
-- MAPEH line as their per-term average (see withDerivedMapeh()).
insert into reg_subjects (code, full_name, abbreviation, category) values
  ('CLE',   'Christian Living Education',                'CLE',   'Core'),
  ('LAN',   'Language',                                  'Lang',  'Core'),
  ('REA',   'Reading',                                   'Rdg',   'Core'),
  ('MAT',   'Mathematics',                               'Math',  'Core'),
  ('FIL',   'Filipino',                                  'Fil',   'Core'),
  ('MUA',   'Music & Arts',                              'MAPEH', 'Core'),
  ('PEH',   'Physical Education & Health',               'MAPEH', 'Core'),
  ('SCI',   'Science',                                   'Sci',   'Core'),
  ('ESP',   'Edukasyon sa Pagpapakatao',                 'EsP',   'Core'),
  ('EPP',   'Edukasyong Pantahanan at Pangkabuhayan',    'EPP',   'Core'),
  ('GMC',   'Good Moral Conduct',                        'GMC',   'Core')
on conflict (code) do nothing;

-- Retire the old single MAPEH subject if a prior run seeded it (grades move to
-- the two components going forward; historical MAPEH grades are unaffected).
delete from reg_subjects where code = 'MAPEH';

-- ── 10. seed: schools master list (transferee origins; real DepEd IDs) ───
insert into reg_schools (code, name, address, district, division, region, type) values
  ('403875', 'Naga Parochial School',                       'Caceres St., Naga City',     'Naga City',  'Naga City',     'V', 'Private'),
  ('403870', 'San Francisco Elementary School',             'San Francisco, Naga City',   'Naga City',  'Naga City',     'V', 'Public'),
  ('410553', 'Calabanga Central School',                    'Calabanga, Camarines Sur',   'Calabanga',  'Camarines Sur', 'V', 'Public'),
  ('433591', 'St. Joseph Academy',                          'Iriga City',                 'Iriga',      'Iriga City',    'V', 'Private'),
  ('436513', 'Holy Rosary Minor Seminary',                  'Naga City',                  'Naga City',  'Naga City',     'V', 'Private'),
  ('436534', 'Bicol University Integrated Laboratory School','Legazpi City',               'Legazpi',    'Albay',         'V', 'SUC')
on conflict (code) do nothing;
